language: java
sudo: false # faster builds
before_install:
- chmod +x mvnw
# script:
# - "./mvnw clean install -B"
# - "./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar"
after_success:
- bash <(curl -s https://codecov.io/bash)
# addons:
#  sonarcloud:
#    organization: prabhakar23-github
#    token:
#      secure: a1c1a29f317e1f44f58560cf99243655fffd3600
deploy:
provider: heroku
api_key:9f3e36c8-2d61-4314-892f-186eecc443bd
app: sprtest23